<a href="https://colab.research.google.com/github/SajjadFakhar/Python-For-fun-/blob/Colab-Codes/Intro_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`Here is the stat of this course for Python`**

In [ ]:
a = 7
b = 7.0
y = 'hehjerfer'


***Type is gonna show the type of the varialbe that we have***

In [ ]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      7
b          float    7.0
y          str      hehjerfer


***Multiple assignments***

In [ ]:
var1,varb = 3 , 5
print(var1,varb)

# Exersize
# overwriting the variable
# using the same variable type
# using the different variable type

var1,varb = 'test' ,65
print(var1,varb)


3 5
test 65


***Math and Printing***

In [ ]:
4+3.033

C = 4+3.03
print(C)

7.029999999999999


In [ ]:
d = 4/3
# if we face a code that it is gonna be too long we can use the back slash \ to go to another line
c = 4 \
+ 3
print(c)
print(d)

7
1.3333333333333333


***Powers***

In [ ]:
3 ** 2
9 ** (1/2)  # square root

3.0

Over loading

In [ ]:
from re import X
firstname = 'Yousef'
secondname = 'alipour'
print(firstname + secondname)
print(firstname +' '+ secondname)
mul = firstname * 3 # it should be an integer but not a float
print(mul)

# Printing the Mathematical Operation
# print('7+3 = 11')
print('7+3 = ' + str(7+3))
x= 7
y = 3
print(str(x) +  '+' +str(y)  +'=' + str(x+y) )

Yousefalipour
Yousef alipour
YousefYousefYousef
7+3 = 10
7+3=10


***Input***

In [ ]:
ans = float(input('Enter a number: '))
print(type(ans))

# INPUT Exersize
# Pythagoren theorem
# Get to iunputs from the user and print the final value
side_1 = float(input('Enter the first side: '))
side_2 = float(input('Enter the second side: '))
hypotenuse = (side_1 ** 2 + side_2 ** 2) ** (1/2)
print('')
print('The hypotenuse is: ' + str(hypotenuse))

Enter a number: 2
<class 'float'>
Enter the first side: 3
Enter the second side: 4

The hypotenuse is: 5.0


**Lists 1/2**

In lists each item will be seprated by a coma and we can make and save differnt type of variables such as nubers and str and so on.
We can also have a list inside another list.

In [ ]:
alist = [2 ,3,35,5]
strlist = ['ali' , 'yousef' , 'taghi']
mixlist = [2 , 'ali' ,3, 'yousef']
print(alist)
print(strlist)
print(mixlist)
listinlist = [3,2,5,['ali','yousef']]
print(listinlist)
another_format_list = [3,                 # here we can add comments
                       2,
                       5,
                        ['ali','yousef']
                       ]
print (another_format_list)

###################################################################
#  if we wanna search inside a list we can try it with ( in ) instead of searching all the lsit
# and also ( not in )
print(2 in alist)
print(2 in strlist)
print('')
print(25 not in alist)
##################################################################
print('')
print("We can also suming the lists together")
print(alist + strlist)
print('')
print('we can also use the multiplication')
print(alist * 3)

[2, 3, 35, 5]
['ali', 'yousef', 'taghi']
[2, 'ali', 3, 'yousef']
[3, 2, 5, ['ali', 'yousef']]
[3, 2, 5, ['ali', 'yousef']]
True
False

True

We can also suming the lists together
[2, 3, 35, 5, 'ali', 'yousef', 'taghi']

we can also use the multiplication
[2, 3, 35, 5, 2, 3, 35, 5, 2, 3, 35, 5]


# **`Method`**

In [ ]:
from pickle import TRUE
# we can add some elements by methods to our list
alist.append('hi')
print(alist)
# we can also count elements of a list
print(alist.count(100))
print('')
# we can also insert of an item to a list but th difference between
# insert and append is that in insert we can assign the position of
# of the new variable
alist.insert(2,565656565)
print(alist)
print('')
# we can also remove an item from the list
alist.remove(2)
print(alist)
# Reversing a list
alist.sort(reverse=TRUE) # i should remove the strigs from the the list becouse methods doe not know how to manage to favce them

print(alist)

[3, 565656565, 565656565, 565656565, 5, 35, 100, 100, 200, 200, 200, 'hi', 'hi', 'hi', 'hi', 'hi', 'hi']
2

[3, 565656565, 565656565, 565656565, 565656565, 5, 35, 100, 100, 200, 200, 200, 'hi', 'hi', 'hi', 'hi', 'hi', 'hi']

[3, 565656565, 565656565, 565656565, 565656565, 5, 35, 100, 100, 200, 200, 200, 'hi', 'hi', 'hi', 'hi', 'hi', 'hi']


TypeError: 'bytes' object cannot be interpreted as an integer

## ***Tuple***

a tuple is like a list but we will use () instead of [].

In [ ]:
atuple = (2,3,4,5,'ali')
print(atuple)
# eve if without using the ( ) also they work
atuple = 2,3,4,5,'ali'
print(atuple)
# we can use the integer multiplication
print(atuple * 3)
print('')
print('')
#
# list is Mutable
# tuple is not Mutable
# Mutable means we can change one variable when we defined it
print(alist)
alist[2] = 100
print(alist)
# now lets see the tuples
print(atuple)
atuple[2] = 100
print(atuple) # for sure there will be an error so it is NoN-mutable


(2, 3, 4, 5, 'ali')
(2, 3, 4, 5, 'ali')
(2, 3, 4, 5, 'ali', 2, 3, 4, 5, 'ali', 2, 3, 4, 5, 'ali')


[3, 565656565, 100, 565656565, 565656565, 5, 35, 100, 100, 200, 200, 200, 'hi', 'hi', 'hi', 'hi', 'hi', 'hi']
[3, 565656565, 100, 565656565, 565656565, 5, 35, 100, 100, 200, 200, 200, 'hi', 'hi', 'hi', 'hi', 'hi', 'hi']
(2, 3, 4, 5, 'ali')


TypeError: 'tuple' object does not support item assignment

## ***Booleans***

it has 2 simple possible values
**True and False**

In [ ]:
t = True    # notice that it should be capital
f = False
print(t)
print(f)
print(type(t))
%whos

True
False
<class 'bool'>
Variable     Type         Data/Info
-----------------------------------
X            RegexFlag    re.VERBOSE
f            bool         False
firstname    str          Yousef
mul          str          YousefYousefYousef
secondname   str          alipour
t            bool         True
var1         str          test
varb         int          65
x            int          7
y            int          3


In [ ]:
# still booleans
# conjuctive comparison
re = 10
re > 5 and re < 15
# or function
re > 5 or re < 4


True

In [ ]:
# Still booleans
# Another possible way to create booleans is using the comprisons
print(3 == 3)     # true
print(3 == 4)     # false
print(3 != 4)     # true
print(3 > 4)      # false
print(3 < 4)      # true
print(3 <= 4)     # true
print(3 >= 4)     # false
print(3 == 3.0)   # true
test = 3 == 3.0
print('test = 3 == 3.0')
print(test)

True
False
True
False
True
True
False
True
test = 3 == 3.0
True


Remember that in Booleans, all the values can go thetough the boolean Function
and the return value will be True, the only value that returns False is 0.
And in the case of strings i should say that they will be true , and the only way to get false is empty cotation.

In [ ]:
print(bool(1))
print(bool(0))
print(bool(2))
print(bool(-1))
print(bool('ali'))
print(bool(''))

True
False
True
True
True
False


In [ ]:
print('Enter 3 numbers: ')
a = float(input(' a = '))
b = float(input(' b = '))
c = float(input(' c = '))
test = (a**2 + b**2 == c**2)
print('your answer is = ' + str(test) +'  !!!')

Enter 3 numbers: 
 a = 3
 b = 4
 c = 5
your answer is = True  !!!


## ***Dictionaries***
In dictionaries we have ( key/value ----> pairs  )
we cannot have values without any keys and we cannot have keys without any values

Dictionaries are mutable


In [ ]:
D = dict()
D # is gonna give a empty dictionary

# [] lists
# () tuples
# {} Dictionaries


{}

In [ ]:
D['name'] = 'yousef'
D['age range'] = [20,50]
D['gender'] = 'male'
D
# thta was an empty dictionary and we add some pairs to that

{'name': 'yousef', 'age range': [20, 50], 'gender': 'male'}

In [ ]:
# here we are gonna create a new dictionaries with some pairs and not initializing as an empty dictionary
E = {'name': 'yousef', 'age range': [20, 50], 'gender': 'male'}
E

{'name': 'yousef', 'age range': [20, 50], 'gender': 'male'}

In [ ]:
# we could achive the keys of a dictionary if we do not know all
keyss = E.keys()
# chcking with ( in )
check_keys = 'name' in E.keys() # it will be working only for keys and working for the values in the key
catch_everything = E.items() # Here it is gonna send back the collection of tuples
# printing the results
print(keyss)
print(check_keys)
check_vales = E.values()
print(check_vales)
print(catch_everything)



dict_keys(['name', 'age range', 'gender'])
True
dict_values(['yousef', [20, 50], 'male'])
dict_items([('name', 'yousef'), ('age range', [20, 50]), ('gender', 'male')])


In [ ]:
# dictionaryy exersize
# 1) input 2 numbers from the user
# 2) create a dictionary with 3 keys : 'first_num' , 'second_num' , 'prodoct'
excersize = dict()
excersize['first_num']  = input()
excersize['second_num'] = input()
excersize['prodoct']    = float(excersize['first_num']) * float(excersize['second_num'])

excersize.items()



5
6


dict_items([('first_num', '5'), ('second_num', '6'), ('prodoct', 30.0)])

***Indexing***

It is what that allow us to access some particular elements of a list or tuple or any data type .
in general ordered items not just list.


In [ ]:
alist = [2,3,4,'Ali',5,6]

# index ofalsit = [0,1,2,3,4,5]
# alist[index_number], It starts from zero
# this feature is gonna work also for tuples
# index also should be also integer

b = alist[3]
print('Length of the list : ',len(alist) ,'the 6th element is :', alist[(len(alist) - 1)])

# or usinf the -1
print(alist[-1])
print(alist[-2])

# we can have lists or dictionaries inside another list
listlist = [4,'hi',[5,4,3] , 'yo' , {'Squirrel' : 'cute' , 'Pinguin' : 'Yummy'}];
# to access the element of another list in this list we can go like this [][]
listlist[2][2 ]

# exercise
listlist[4]['Pinguin']
D = listlist[4]
D['Pinguin']

Length of the list :  6 the 6th element is : 6
6
5


'Yummy'

## `Slicing`
it is about a precedure on list, touples and numpy array and matrices that allow us to allow you to access Multiple elements at the same time

In [ ]:
# Range is gonna create a set of integers , starting from the first number up to the last number but excluding the last number
range_list = list(range(5,11)) # this set is gonna be from 5 to 10
print('range_list = ',range_list)
# in slicing we have the lower bound the upper bound
print('sliced list is equal : ',range_list[0:3]) # upper bound is exclusive

print('sliced list is equal : ',range_list[:3]) # from 0 to 3

print('sliced list is equal : ',range_list[2:3]) # from 2 to 3

print('sliced list is equal : ',range_list[3:]) # from 3 to the end

# now we wanna have every other elements
print('sliced list is equal : ',range_list[::2])

# now every other element but starting from first indice
print('sliced list is equal : ',range_list[1::2])

# how the python is gonna behave is like this
#          list[start:stop:skip]
start = 0 # start from this indice
stop  = 2 # stop in this indice
skip  = 2 # skip the first but consider the second
print('sliced list is equal : ',range_list[start:stop:skip])

# now we are gonna reverse a list
print('reversed list is equal : ',range_list[::-1])


range_list =  [5, 6, 7, 8, 9, 10]
sliced list is equal :  [5, 6, 7]
sliced list is equal :  [5, 6, 7]
sliced list is equal :  [7]
sliced list is equal :  [8, 9, 10]
sliced list is equal :  [5, 7, 9]
sliced list is equal :  [6, 8, 10]
sliced list is equal :  [5]
reversed list is equal :  [10, 9, 8, 7, 6, 5]


0

In [ ]:
# Exercize
text = '4787049433 si Dajjas eman'
print(text[::-1])
exercize = list(text)
print(exercize[::-1])
start = -1 # start from this indice
stop  = 13 # stop in this indice
skip  = -1 # skip the first but consider the second
#print('sliced list is equal : ',text[start:stop:skip])
print(text[start:stop:skip])
the_list =list(range(2,20))
print(the_list)
 # if we have something like this [  [2,3,5]  ] so we need to use the list comprehension


name sajjaD is 3349407874
['n', 'a', 'm', 'e', ' ', 's', 'a', 'j', 'j', 'a', 'D', ' ', 'i', 's', ' ', '3', '3', '4', '9', '4', '0', '7', '8', '7', '4']
name sajjaD
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


# ***input and output***

From now on remeber that the functions have pranthesis for getting the input

In [ ]:
# Sum function
VAR = [10,20,30] # it will be working on the floats and integers
print('Output = ',sum(VAR) , 'IT WILL BE THE SUM OF THE LIST')

# it doesnt work on the strings
#VAR_str = [10,20,30,'ali']
#print('SUM = ',sum(VAR_str) , 'IT WILL BETHE SUM OF THE LIST')

# it doesn't work on the list in the list
#VAR_in_list = [10,20,30,[2,3,2]]
#print('SUM = ',sum(VAR_in_list) , 'IT WILL BETHE SUM OF THE LIST')


Output =  60 IT WILL BE THE SUM OF THE LIST


### **Numpy Library**

In [ ]:
import numpy as np  # Numerical Python
#from numpy import .... #it means i do not need all thsi library and i only need this specific funtion

numbers = [1,3,2,4,5]
np.mean(numbers)

# linespace is gonna give a linearly spaced numbers from a to b and how many of them
line_space = np.linspace(0,100,10)
print(line_space)
print(type(line_space)) # nd is for n dimensional
# we can also change the type of the variable in numpy library
numbers_np = np.array(numbers)
print('')
print(type(numbers))
print('')
print(numbers_np)
print(type(numbers_np))
numbers_np.mean()
print(numbers_np.mean()) # sum of all elements divided by number of elements
print(numbers_np.max())
print(numbers_np.min())
print(numbers_np.std()) # compute standard deviation
print(numbers_np.var()) # compute the vaiance

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
<class 'numpy.ndarray'>

<class 'list'>

[1 3 2 4 5]
<class 'numpy.ndarray'>
3.0
5
1
1.4142135623730951
2.0


In [ ]:
# in place operations
# out-of-place / not in-place operations


### ***Pandas***
it will give an access to the packages that are specificly for the data sets as observations by features
so any kind of data that could be represented by spreadsheets.
so data will be put in a 2 dimensional matrix.
where the rows would be observations and columns would be features

In [ ]:
import pandas as pd
import numpy as np
# create random data
a = np.random.randn()   # here it alone will return just a number
c = np.random.randn(5)  # if there is a value it will return as many as random values as the number is
print(a)
print(" n random numbers are : ",c)
print(type(c))
d = np.random.randn(5,4) # it will give an n * n matrix of random numbers
print(d)
print(type(d))
print('')
var1 = np.random.randn(100) * 5 + 20
#print(var1)
var2 = np.random.randn(100) > 0 # it will be true or false
#print(var2)
lables = ['tep (c) ','ice cream '];

# put them toghether in a dictionary
D = {lables[0] : var1 , lables[1] : var2}
print(D)

print('')
# import the dictionary to a pandas dataframe
df = pd.DataFrame(data = D) # DataFrame is fucntion of the panda data frame library
print(type(df))
print(df)



-0.201258525096716
 n random numbers are :  [ 0.40780697 -2.01980222  1.07504402 -0.34585501 -1.55316433]
<class 'numpy.ndarray'>
[[-1.05245525  1.99845204 -0.35558801 -0.11811414]
 [-1.80957194  0.39971736  0.12043914 -1.28397754]
 [ 0.26287459 -1.01454974  1.03037912 -0.2726829 ]
 [ 0.96116942  1.41520852  0.50943867  0.01154428]
 [ 1.17352542  0.36862553 -1.48807296 -1.10373192]]
<class 'numpy.ndarray'>

{'tep (c) ': array([22.203654  , 23.53769268, 30.20559822, 23.20218428, 25.51156371,
       10.66534821, 16.89226913, 32.63424126, 24.73764463, 18.85398743,
       10.03132742, 21.17155536, 25.04207592, 14.79768836, 23.80961881,
       24.89005496, 24.99432658, 13.87459843, 22.5322287 , 17.15907721,
       12.35294312, 10.05037067, 25.21454648, 13.04959918, 13.44107679,
       27.3153009 , 20.42976488, 13.14403705, 17.34342972, 19.96126891,
       20.1649017 , 22.89127815, 14.72249485, 21.32506013, 16.12714279,
       31.21409185, 24.68298313, 18.02960394, 20.84101793, 21.08858194,


In [ ]:
#instead of that we can print the headers or the top of this data set
print(df.head())
print('')
# we can count the number of the observations that we have
print(df.count())
print('')
# we can have the average value
print(df.mean())

    tep (c)   ice cream 
0  22.203654        True
1  23.537693       False
2  30.205598       False
3  23.202184        True
4  25.511564       False

tep (c)       100
ice cream     100
dtype: int64

tep (c)       20.165901
ice cream      0.480000
dtype: float64


In [ ]:
# exersize
# create a pandas datafram with :
# integers goes from 0 to 10, their square, and their log

integers = np.array(range(11))
print(integers)

their_square = integers ** 2
print(their_square)

their_log = np.log(integers)
print(their_log)

labales = ['Square' , 'Logarithm'];
Dct = {labales[0] : their_square , labales[1] : their_log}
print(Dct)
df = pd.DataFrame(data = Dct)
print(df)
print('')
print('Head = ',df.head())
print('')
print('count = ',df.count())
print('')
print('Mean = ',df.mean())

[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1   4   9  16  25  36  49  64  81 100]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
{'Square': array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]), 'Logarithm': array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])}
    Square  Logarithm
0        0       -inf
1        1   0.000000
2        4   0.693147
3        9   1.098612
4       16   1.386294
5       25   1.609438
6       36   1.791759
7       49   1.945910
8       64   2.079442
9       81   2.197225
10     100   2.302585

Head =     Square  Logarithm
0       0       -inf
1       1   0.000000
2       4   0.693147
3       9   1.098612
4      16   1.386294

count =  Square       11
Logarithm    11
dtype: int64

Mean =  Square       35.0
Logarithm    -inf
dtype: float64


<ipython-input-17-894efb99ecca>:11: RuntimeWarning: divide by zero encountered in log
  their_log = np.log(integers)
